from __future__ import annotations

from .document_utils import (
    _build_metadata,
    _doc_signature,
    _docs_from_text,
    _format_context,
    _format_source,
    _merge_docs,
    _response_text,
    _unique_sources,
)
from .extractors import (
    _extract_doc_text,
    _extract_doc_with_soffice,
    _extract_doc_with_textract,
    _extract_doc_with_word,
    _extract_docx_text,
    _extract_excel_text,
)
from .file_utils import _read_text_with_fallback, _write_text
from .keyword_utils import (
    _cjk_ngrams,
    _docs_have_keyword_hits,
    _extract_source_hint,
    _filter_docs_by_source_hint,
    _keyword_fallback,
    _keyword_score,
    _latin_keywords,
    _query_terms,
)
from .ocr_utils import _LazyOCR, _extract_text_from_file
from .source_processing import _load_cached_text, process_sources
from .text_utils import (
    _cjk_count,
    _ensure_page_markers,
    _garbled_score,
    _join_pages,
    _looks_garbled,
    _maybe_repair_mojibake,
    _normalize_text,
    _split_pages,
)
from .vectorstore_utils import (
    _build_index_manifest,
    _collection_exists,
    _docs_from_search_results,
    _fingerprint_processed,
    _get_qdrant_client,
    _hybrid_rerank,
    _keyword_scores_for_docs,
    _load_manifest,
    _manifest_matches,
    _normalize_scores,
    _qdrant_location,
    _recreate_collection,
    _save_manifest,
    _search_qdrant,
    _upsert_documents,
)

__all__ = [
    "_LazyOCR",
    "_build_index_manifest",
    "_build_metadata",
    "_cjk_count",
    "_cjk_ngrams",
    "_collection_exists",
    "_doc_signature",
    "_docs_from_search_results",
    "_docs_from_text",
    "_docs_have_keyword_hits",
    "_ensure_page_markers",
    "_extract_doc_text",
    "_extract_doc_with_soffice",
    "_extract_doc_with_textract",
    "_extract_doc_with_word",
    "_extract_docx_text",
    "_extract_excel_text",
    "_extract_source_hint",
    "_extract_text_from_file",
    "_filter_docs_by_source_hint",
    "_fingerprint_processed",
    "_format_context",
    "_format_source",
    "_garbled_score",
    "_get_qdrant_client",
    "_hybrid_rerank",
    "_join_pages",
    "_keyword_fallback",
    "_keyword_score",
    "_keyword_scores_for_docs",
    "_latin_keywords",
    "_load_cached_text",
    "_load_manifest",
    "_looks_garbled",
    "_manifest_matches",
    "_merge_docs",
    "_maybe_repair_mojibake",
    "_normalize_scores",
    "_normalize_text",
    "_qdrant_location",
    "_query_terms",
    "_read_text_with_fallback",
    "_recreate_collection",
    "_response_text",
    "_save_manifest",
    "_search_qdrant",
    "_split_pages",
    "_unique_sources",
    "_upsert_documents",
    "_write_text",
    "process_sources",
]
